// HOME PAGE PRODUCT LISTING
export const GET_HOME_PAGE_PRODUCTS = 'GET_HOME_PAGE_PRODUCTS';
export const GET_HOME_PAGE_PRODUCTS_SUCCESS = 'GET_HOME_PAGE_PRODUCTS_SUCCESS';
export const GET_HOME_PAGE_PRODUCTS_FAILURE = 'GET_HOME_PAGE_PRODUCTS_FAILURE';
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS';

// SINGLE PRODUCT LISTING
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS';
export const GET_SINGLE_PRODUCT_FAILURE = 'GET_SINGLE_PRODUCT_FAILURE';
export const RESET_SINGLE_PRODUCT = 'RESET_SINGLE_PRODUCT';
export const LOADING_PRODUCT = 'LOADING_PRODUCT';

// CART ACTIONS
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';

export const ADD_ONE = 'ADD_ONE';
export const REMOVE_ONE = 'REMOVE_ONE';

export const EMPTY_BASKET = 'EMPTY_BASKET';
